name: Publish Package
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Is this a dry run. If so no package will be published.'
        type: boolean
        required: true

jobs:
  build-publish:
    runs-on: ubuntu-latest
    # Needed to get tokens during publishing.
    permissions:
      id-token: write
      contents: read
      attestations: write # Needed for actions/attest
    steps:
      - uses: actions/checkout@v4

      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
        name: 'Get rubygems API key'
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: '/production/common/releasing/rubygems/api_key = GEM_HOST_API_KEY'

      - name: Build and Test
        uses: ./.github/actions/ci
        with:
          ruby-version: 3.0

      - name: Publish Package
        uses: ./.github/actions/publish
        with:
          dry_run: ${{ inputs.dry_run }}

      - name: Attest build provenance
        if: ${{ format('{0}', inputs.dry_run) == 'false' }}
        uses: actions/attest@v4
        with:
          subject-path: 'launchdarkly-server-sdk-otel-*.gem'
